def test_function():
    def inner_function():
        print("Я в области видимости функции test_function")

    # Вызов вложенной функции внутри test_function
    inner_function()

# Вызов функции test_function
 test_function()

# Попытка вызвать inner_function вне области видимости test_function
try:
    inner_function()
except NameError as e:
    print(f"Ошибка: {e}")
